services:
  # O Web Service continua igual
  - type: web
    name: painel-emails-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

  # MUDANÇA: Substituímos o 'worker' por 'cron'
  - type: cron
    name: painel-emails-cron
    env: python
    plan: free
    # A agenda está no formato UTC. '*/15 * * * *' significa "a cada 15 minutos".
    schedule: "*/15 * * * *"
    # O comando é o mesmo, ele apenas rodará o script uma vez.
    command: "python worker.py"
