services:
  # Define o serviço da interface web (app.py)
  - type: web
    name: painel-emails-web
    env: python
    plan: free # Especifica o plano gratuito
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

  # Define o robô de automação como um Cron Job
  - type: cron
    name: painel-emails-cron
    env: python
    plan: free # Cron Jobs também estão no plano gratuito
    # Agenda para rodar a cada 15 minutos
    schedule: "*/15 * * * *"
    # Comando que será executado
    command: "python worker.py"
