# O 'services' define tudo o que vamos criar no Render.
services:
  # Primeiro, definimos nossa interface web (o app.py)
  - type: web
    name: painel-emails-web
    env: python
    # Especifica o plano gratuito
    plan: free
    # Comando para instalar as bibliotecas
    buildCommand: "pip install -r requirements.txt"
    # Comando para iniciar o servidor de produção
    startCommand: "gunicorn app:app"

  # Em segundo lugar, definimos nosso robô (o worker.py)
  - type: worker
    name: painel-emails-worker
    env: python
    # Especifica o plano gratuito também para o robô
    plan: free
    # O worker usa as mesmas bibliotecas, então o comando é o mesmo
    buildCommand: "pip install -r requirements.txt"
    # Comando para iniciar o robô
    startCommand: "python worker.py"
